### ISSUE TITLE
Composite Product dropdowns

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#17]
I can see that finally the dropdowns for the composite products are working, but they lost all the styling.
![screenshot 2015-06-10 10 31 42](https://cloud.githubusercontent.com/assets/3596525/8083554/e082d692-0f5b-11e5-94c5-bce30e031749.png)

**Comment by leninlee** [comment]
![Uploading Screenshot_061515_062617_PM.jpg…]()
Fixed
![screenshot_061515_062031_pm](https://cloud.githubusercontent.com/assets/5433592/8160210/56490cf6-138b-11e5-983e-367aa000d909.jpg)
![screenshot_061515_062105_pm](https://cloud.githubusercontent.com/assets/5433592/8160211/5724a3e2-138b-11e5-8fc4-7530735f5899.jpg)

**Comment by ortokore** [comment]
Not fixed?

![screenshot 2015-06-15 12 43 51](https://cloud.githubusercontent.com/assets/3596525/8163902/32bd1e6e-135c-11e5-8621-11c9db3caf1f.png)

**Comment by leninlee** [comment]
Pls!  Tell me product URL?

**Comment by ortokore** [comment]
http://gs-openboxstore.cl.s207584.gridserver.com/shop/longboard/loaded-cantellated-tesseract-deck-2/

**Comment by ortokore** [comment]
What's going on with this? it looks worse than yesterday.

**Comment by leninlee** [comment]
![screenshot_061615_101718_pm](https://cloud.githubusercontent.com/assets/5433592/8189835/914d91f4-147c-11e5-89b9-b29ceff6c54f.jpg)
